USE NORMALIZED_INVOICE;

-- FORMA CLASSICA DE CONSULTAS COMBINADAS
SELECT INVOICE.*, INVOICE_ITEM.* 
FROM INVOICE, INVOICE_ITEM
WHERE INVOICE.INVOICE_NUMBER = INVOICE_ITEM.INVOICE_NUMBER;

-- PODEMOS DEFINIR ALIAS (APELIDOS) PARA AS TABELAS E FACILITAR A CODIFICACAO
SELECT INV.INVOICE_NUMBER , INV.ISSUE_DATE , INV.TOTAL_VALUE , INV_ITEM.PRODUCT_CODE , 
		INV_ITEM.PRODUCT_QUANTITY , INV_ITEM.UNIT_PRICE , INV_ITEM.TOTAL_PRICE , PROD.PRODUCT_DESC , PROD.UNIT_MEASURE 
FROM 
	INVOICE AS INV, 
    INVOICE_ITEM AS INV_ITEM,
    PRODUCT AS PROD
WHERE 
	INV.INVOICE_NUMBER = INV_ITEM.INVOICE_NUMBER
	AND INV_ITEM.PRODUCT_CODE = PROD.PRODUCT_CODE
ORDER BY 
	INV.INVOICE_NUMBER DESC, INV_ITEM.PRODUCT_CODE ASC;

-- INNER JOIN 
SELECT INV.INVOICE_NUMBER , INV.ISSUE_DATE , INV.TOTAL_VALUE , INV_ITEM.PRODUCT_CODE , 
		INV_ITEM.PRODUCT_QUANTITY , INV_ITEM.UNIT_PRICE , INV_ITEM.TOTAL_PRICE , PROD.PRODUCT_DESC , PROD.UNIT_MEASURE 
FROM 
	INVOICE AS INV 
    INNER JOIN
		INVOICE_ITEM AS INV_ITEM ON INV.INVOICE_NUMBER = INV_ITEM.INVOICE_NUMBER
	INNER JOIN
		PRODUCT AS PROD ON INV_ITEM.PRODUCT_CODE = PROD.PRODUCT_CODE
WHERE INV.INVOICE_NUMBER = 4
ORDER BY 
	INV.INVOICE_NUMBER DESC, INV_ITEM.PRODUCT_CODE ASC;
    
-- FUNCOES DE AGREGACAO
-- CONTANDO E QUNATIFICANDO REGISTROS

-- QUANTAS NOTAS FISCAIS TEM EMITIDAS?
SELECT COUNT(*) 
FROM INVOICE;

-- NOTAS FISCAIS POR PERIODO
SELECT COUNT(*)
FROM INVOICE
WHERE ISSUE_DATE > '2025-03-21-' AND ISSUE_DATE < '2025-03-25';

-- USANDO BETWEEN (MENOR AND MAIOR)
SELECT COUNT(*)
FROM INVOICE
WHERE ISSUE_DATE BETWEEN '2025-03-21-' AND '2025-03-25';

-- TOTAL DE NOTAS NO ANO
SELECT COUNT(*)
FROM INVOICE
WHERE YEAR(ISSUE_DATE) = 2025;

-- MAX( ) -> OBTENDO O CLIENTE QUE MAIS COMPROU DETERMINADO PRODUTO EM UMA UNICA NOTA FISCAL
SELECT 
	INV.CUSTOMER_NAME AS CUSTOMER, 
    PROD.PRODUCT_DESC AS PRODUCT,
    MAX(PRODUCT_QUANTITY) AS QUANTITY
FROM INVOICE_ITEM AS INV_ITEM
INNER JOIN INVOICE AS INV 
	ON INV_ITEM.INVOICE_NUMBER = INV.INVOICE_NUMBER
INNER JOIN PRODUCT AS PROD
	ON INV_ITEM.PRODUCT_CODE = PROD.PRODUCT_CODE
-- WHERE INV_ITEM.PRODUCT_CODE = 2
GROUP BY INV.CUSTOMER_NAME, PROD.PRODUCT_DESC
ORDER BY CUSTOMER, QUANTITY DESC;
